---
headingMaxLength: 60
excludePatterns:
- ".git"
- "/template"

basePath: content/tutorials/portenta-h7/
allowedSyntaxSpecifiers:
- cpp
- py
- text

allowNestedLists: false
metadataSchema: scripts/validation/config/metadata-schema.json
checkForBrokenLinks: true
brokenLinkExcludePatterns:
- assets/

verboseOutput: true
