---
- regex: "[bB]luetooth[^速]|bluetooth"
  shouldMatch: false
  format: markdown
  errorMessage: The Bluetooth速 trademark is not used correctly.
  
- regex: "[lL]o[rR]a[^速]|lora"
  shouldMatch: false
  format: markdown
  errorMessage: The LoRa速 trademark is not used correctly.
