---
- regex: "\\*\\*Authors:\\*\\* .*  \\n"
  shouldMatch: true
  format: markdown
  errorMessage: The authors' format is incorrect. Trailing spaces missing?

- regex: "#### .*\\n"
  shouldMatch: false
  format: markdown
  errorMessage: H4 headings are not supported.

- regex: "\\*\\*Reviewed by:\\*\\* .* \\[\\d\\d\\d?\\d\\-\\d?\\d\\-\\d\\d\\]  \\n"
  shouldMatch: true
  format: markdown
  errorMessage: The reviewer's format is incorrect. Review date added YYYY-MM-DD?

- regex: "\\*\\*Last revision:\\*\\* .* \\[\\d\\d\\d?\\d\\-\\d?\\d\\-\\d\\d\\]"
  shouldMatch: true
  format: markdown
  errorMessage: The revisor's format is incorrect. Revision date correct YYYY-MM-DD?

- regex: "\\n## Conclusion\\n"
  shouldMatch: true
  format: markdown
  errorMessage: Missing conclusion section.

- regex: "\\n### You Will Learn\\n"
  shouldMatch: true
  format: markdown
  errorMessage: Missing 'What You Will Learn' section.

- regex: "\\n### Required Hardware and Software\\n"
  shouldMatch: true
  format: markdown
  errorMessage: Missing 'Required Hardware and Software' section.

- regex: "(?<=\\s)\\*[^* ].*\\*[^*]"
  shouldMatch: false
  format: markdown
  errorMessage: The use of italic emphasis is discouraged.

- regex: "(?<=\\s)_[^_].*_[^_]"
  shouldMatch: false
  format: markdown
  errorMessage: The use of italic emphasis is discouraged.

- regex: "\\*\\*\\*(?: +\\S+)|(?:\\S+ +)\\*\\*\\*"
  shouldMatch: false
  format: markdown
  errorMessage: Whitespaces are not allowed at the beginning or end of a note block.
